name: ditect file change

on:
  push:
    branches:
      - main
    paths:
      - 'sample.txt'

jobs:
  detect-file-change:
    runs-on: ubuntu-latest
    steps:
      - name: detect
        run: echo detect file change!
